In [1]:
# importando a biblioteca Pandas
import pandas as pd

In [19]:
# Lendo arquivos HTML
df = pd.read_html('https://gist.github.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6')[0]

In [27]:
df.isnull().sum()

Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Ataque          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [22]:
# renomeando colunas
df.rename(columns={'Attack': 'Ataque'}, inplace=True)

# removendo colunas
df.drop(columns=['Unnamed: 0', '#'], inplace=True)

In [23]:
df

,Name,Type 1,Type 2,Total,HP,Ataque,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [24]:
# agrupando dados
df.groupby('Type 1').mean()

<ipython-input-24-88fccc054cb6>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Type 1').mean()

,Total,HP,Ataque,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Dragon,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Electric,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Fighting,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fire,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Ghost,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Grass,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ground,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ice,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Normal,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Poison,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Psychic,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Rock,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Water,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714

In [25]:
#Mais flexivel ainda, podemos escolher o tipo de operaÃ§ao por coluna
df.groupby('Type 1').aggregate({"Ataque" : "mean"
                                   , "Defense" : "median"
                                   , "Speed" : "max"})

              Ataque  Defense  Speed
Type 1
Bug        70.971014     60.0    160
Dark       88.387097     70.0    125
Dragon    112.125000     90.0    120
Electric   69.090909     65.0    140
Fairy      61.529412     66.0     99
Fighting   96.777778     70.0    118
Fire       84.769231     64.0    126
Flying     78.750000     75.0    123
Ghost      73.781250     72.5    130
Grass      73.214286     66.0    145
Ground     95.750000     84.5    120
Ice        72.750000     75.0    110
Normal     73.469388     60.0    135
Poison     74.678571     67.0    130
Psychic    71.456140     65.0    180
Rock       92.863636    100.0    150
Steel      92.703704    120.0    110
Water      74.151786     70.0    122